# Generated by Django 5.1.2 on 2024-10-19 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_is_active_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('stock_status', models.BooleanField(default=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('main_image', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.supplier')),
            ],
            options={
                'permissions': [('can_add_product', 'Can add product'), ('can_edit_product', 'Can edit product'), ('can_delete_product', 'Can delete product')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'product_code'), name='unique_product_code_per_supplier')],
            },
        ),
    ]
